const translations = {
    es: {
        // Página Principal
        "main_title": "Coffee Tours",
        "welcome_text": "Coffee Tours es un concepto innovador, de agencia de viajes y café!",
        "search_placeholder": "Buscar...",
        "search_button": "Buscar",
        "view_button": "Ver",
        "quote_button": "Cotizar",
        "book_button": "Reservar",
        "promotions_title": "Promociones",
        "paris_title": "París",
        "paris_alt": "París",
        "cuba_title": "Cuba",
        "cuba_alt": "Cuba",
        "cozumel_title": "Cozumel",
        "cozumel_alt": "Cozumel",
        "promo1_title": "Oferta Especial París",
        "promo1_text": "¡30% de descuento en tours por la ciudad!",
        "promo2_title": "2x1 en Cuba",
        "promo2_text": "Lleva a un acompañante gratis",
        "promo3_title": "Paquete Cozumel",
        "promo3_text": "Todo incluido desde $999",
        "promo4_title": "Oferta Especial",
        "promo4_text": "Descuentos exclusivos",
        "promo5_title": "Oferta de Temporada",
        "promo5_text": "Paquetes especiales",
        "oferta1_alt": "Oferta París",
        "oferta2_alt": "Oferta Cuba",
        "oferta3_alt": "Oferta Cozumel",
        "oferta4_alt": "Oferta Especial",
        "oferta5_alt": "Oferta Temporada",

        // Página de Reserva
        "booking_title": "Reserva",
        "destination": "Destino: Roma, Italia.",
        "italy_img_alt": "Roma, Italia",
        "tab_description": "Descripción",
        "tab_itinerary": "Itinerario",
        "tab_prices": "Precios",
        "tab_testimonials": "Testimonios",
        "tour_description": "Descubre la majestuosidad de Roma, un destino donde la historia cobra vida. Pasea por el Coliseo, lanza una moneda en la Fontana di Trevi y maravíllate con la grandeza del Vaticano. Disfruta de la auténtica gastronomía italiana con pizzas, pastas y gelato mientras exploras sus encantadoras calles empedradas.",
        "print_button": "Imprimir",
        "base_price": "$ Precio base",
        "start_date": "Fecha de inicio",
        "duration": "Duración",
        "duration_value": "6 días, 5 noches",
        "people": "Personas",
        "option_1_person": "1 persona",
        "option_2_people": "2 personas",
        "option_3_people": "3 personas",
        "option_4_people": "4 personas",
        "option_5_people": "5 personas",
        "total": "Total",
        "continue_button": "Continuar reserva",

        // Página de Contacto
        "contact_title": "Contáctanos",
        "schedule_time": "9:00 am - 6:00 pm",
        "schedule_days": "De Lunes a Viernes",
        "social_title": "Redes sociales",
        "instagram_handle": "agenciadeviajes_coffeetours",
        "facebook_handle": "Coffee Tours Agencia de Viajes",
        "location_title": "Ubicación",
        "map_alt": "Ubicación de Coffee Tours",
        "form_title": "Formulario de contacto",
        "name_label": "Nombre y apellidos *",
        "email_label": "Email *",
        "country_label": "País *",
        "phone_label": "Teléfono *",
        "comments_label": "Observaciones",
        "submit_button": "Enviar",

        // Página de Checkout
        "checkout_title": "Finalizar Compra",
        "billing_title": "Detalles de facturación",
        "name_label": "Nombre *",
        "lastname_label": "Apellidos *",
        "country_label": "País/Región *",
        "phone_label": "Teléfono *",
        "email_label": "Dirección de correo electrónico *",
        "additional_info": "Información adicional",
        "your_order": "Tu pedido",
        "product": "Producto",
        "description": "Descripción",
        "from": "De: Ciudad de México",
        "to": "A: Roma, Italia",
        "duration": "Duración: 6 días, 5 noches",
        "persons": "Personas: 3",
        "subtotal": "Subtotal",
        "payment_method": "¿Cómo desea pagar?",
        "terms_conditions": "Términos y Condiciones",
        "place_order": "Realizar pedido",

        // Página de Registro
        "register_title": "Crear cuenta / Registro",
        "username_label": "Nombre de usuario:",
        "email_label": "Email:",
        "password_label": "Contraseña:",
        "confirm_password_label": "Confirmar contraseña:",
        "register_button": "Registrarse",
        "terms_text": "Al continuar, declaras que leíste y aceptas nuestros",
        "terms_link": "Términos y condiciones",
        "privacy_link": "Aviso de privacidad",
        "password_mismatch": "Las contraseñas no coinciden",
        "password_length": "La contraseña debe tener al menos 8 caracteres",
        "invalid_email": "Ingresa un correo válido",

        // Página de Inicio de Sesión
        "login_title": "Iniciar Sesión",
        "username": "Usuario",
        "password": "Contraseña",
        "login_button": "Iniciar Sesión",
        "no_account": "¿No tienes una cuenta?",
        "register_link": "¡Regístrate!",
        "username_placeholder": "Ingresa tu nombre de usuario",
        "password_placeholder": "Ingresa tu contraseña",

        // Página de Reseñas
        "reviews_page_title": "Reseñas y comentarios",
        "reviews_title": "Reseñas y comentarios",
        "review_title_1": "¡Increíble experiencia!",
        "review_text_1": "¡Excelente servicio! La agencia me ayudó a planear un viaje increíble. Todo estuvo perfectamente organizado.",
        "review_date_1": "15 de octubre, 2023",
        "review_title_2": "Vacaciones perfectas",
        "review_text_2": "Todo salió exactamente como lo planeamos. El equipo fue muy profesional y atento.",
        "review_date_2": "5 de noviembre, 2023",
        "review_title_3": "Recomendado 100%",
        "review_text_3": "No podría haber pedido un mejor servicio. Cada detalle fue cuidado al máximo.",
        "review_date_3": "20 de diciembre, 2023",
        "review_title_4": "Experiencia única",
        "review_text_4": "Los tours de café fueron educativos y deliciosos. Aprendí mucho sobre el proceso del café.",
        "review_date_4": "10 de enero, 2024",
        "review_title_5": "Excelente organización",
        "review_text_5": "Todo estuvo perfectamente coordinado. Los guías eran conocedores y amigables.",
        "review_date_5": "5 de febrero, 2024",
        "review_title_6": "Volvería sin dudarlo",
        "review_text_6": "La combinación de viajes y café es genial. Los paisajes eran impresionantes.",
        "review_date_6": "15 de marzo, 2024",
        "review_title_7": "Servicio excepcional",
        "review_text_7": "El personal fue muy atento y resolvió todas nuestras dudas rápidamente.",
        "review_date_7": "1 de abril, 2024",
        "review_title_8": "Viaje inolvidable",
        "review_text_8": "Una experiencia que repetiría sin dudarlo. Todo estuvo perfectamente planeado.",
        "review_date_8": "20 de abril, 2024",

        // Elementos comunes
        "contact": "Contacto",
        "reviews": "Reseñas y Comentarios",
        "about": "Sobre Nosotros",
        "help": "Ayuda",
        "footer_address": "Av. Colón Num, 200 Centro, Tepeaca, Mexico",
        "footer_phone": "Teléfono: 223 101 1997",
        "footer_email": "Correo: coffeetours.puebla@gmail.com",
        "reviews_link": "Reseñas y Comentarios",
        "about_link": "Sobre Nosotros",
        "footer_disclaimer": "Coffee Tours no es responsable del contenido de los sitios web externos.",
        "footer_copyright": "© 2025 Coffee Tours. Todos los derechos reservados.",
        "help_text": "Ayuda"
    },
    en: {
        // Página Principal
        "main_title": "Coffee Tours",
        "welcome_text": "Coffee Tours is an innovative concept, combining travel agency and coffee!",
        "search_placeholder": "Search...",
        "search_button": "Search",
        "view_button": "View",
        "quote_button": "Quote",
        "book_button": "Book Now",
        "promotions_title": "Promotions",
        "paris_title": "Paris",
        "paris_alt": "Paris",
        "cuba_title": "Cuba",
        "cuba_alt": "Cuba",
        "cozumel_title": "Cozumel",
        "cozumel_alt": "Cozumel",
        "promo1_title": "Special Paris Offer",
        "promo1_text": "30% discount on city tours!",
        "promo2_title": "2x1 in Cuba",
        "promo2_text": "Bring a companion for free",
        "promo3_title": "Cozumel Package",
        "promo3_text": "All inclusive from $999",
        "promo4_title": "Special Offer",
        "promo4_text": "Exclusive discounts",
        "promo5_title": "Seasonal Offer",
        "promo5_text": "Special packages",
        "oferta1_alt": "Paris Offer",
        "oferta2_alt": "Cuba Offer",
        "oferta3_alt": "Cozumel Offer",
        "oferta4_alt": "Special Offer",
        "oferta5_alt": "Seasonal Offer",

        // Página de Reserva
        "booking_title": "Booking",
        "destination": "Destination: Rome, Italy.",
        "italy_img_alt": "Rome, Italy",
        "tab_description": "Description",
        "tab_itinerary": "Itinerary",
        "tab_prices": "Prices",
        "tab_testimonials": "Testimonials",
        "tour_description": "Discover the majesty of Rome, a destination where history comes to life. Walk through the Colosseum, toss a coin in the Trevi Fountain and marvel at the grandeur of the Vatican. Enjoy authentic Italian cuisine with pizzas, pastas and gelato as you explore its charming cobblestone streets.",
        "print_button": "Print",
        "base_price": "$ Base price",
        "start_date": "Start date",
        "duration": "Duration",
        "duration_value": "6 days, 5 nights",
        "people": "People",
        "option_1_person": "1 person",
        "option_2_people": "2 people",
        "option_3_people": "3 people",
        "option_4_people": "4 people",
        "option_5_people": "5 people",
        "total": "Total",
        "continue_button": "Continue booking",

        // Página de Contacto
        "contact_title": "Contact Us",
        "schedule_time": "9:00 am - 6:00 pm",
        "schedule_days": "Monday to Friday",
        "social_title": "Social Media",
        "instagram_handle": "travelagency_coffeetours",
        "facebook_handle": "Coffee Tours Travel Agency",
        "location_title": "Location",
        "map_alt": "Coffee Tours Location",
        "form_title": "Contact Form",
        "name_label": "Full Name *",
        "email_label": "Email *",
        "country_label": "Country *",
        "phone_label": "Phone *",
        "comments_label": "Comments",
        "submit_button": "Submit",

        // Página de Checkout
        "checkout_title": "Checkout",
        "billing_title": "Billing Details",
        "name_label": "First Name *",
        "lastname_label": "Last Name *",
        "country_label": "Country/Region *",
        "phone_label": "Phone *",
        "email_label": "Email Address *",
        "additional_info": "Additional Information",
        "your_order": "Your Order",
        "product": "Product",
        "description": "Description",
        "from": "From: Mexico City",
        "to": "To: Rome, Italy",
        "duration": "Duration: 6 days, 5 nights",
        "persons": "Persons: 3",
        "subtotal": "Subtotal",
        "payment_method": "Payment Method",
        "terms_conditions": "Terms and Conditions",
        "place_order": "Place Order",

        // Página de Registro
        "register_title": "Create Account / Register",
        "username_label": "Username:",
        "email_label": "Email:",
        "password_label": "Password:",
        "confirm_password_label": "Confirm password:",
        "register_button": "Sign Up",
        "terms_text": "By continuing, you declare that you have read and accept our",
        "terms_link": "Terms and conditions",
        "privacy_link": "Privacy notice",
        "password_mismatch": "Passwords do not match",
        "password_length": "Password must be at least 8 characters",
        "invalid_email": "Enter a valid email",

        // Página de Inicio de Sesión
        "login_title": "Login",
        "username": "Username",
        "password": "Password",
        "login_button": "Sign In",
        "no_account": "Don't have an account?",
        "register_link": "Register now!",
        "username_placeholder": "Enter your username",
        "password_placeholder": "Enter your password",

        // Página de Reseñas
        "reviews_page_title": "Reviews and Comments",
        "reviews_title": "Reviews and Comments",
        "review_title_1": "Amazing experience!",
        "review_text_1": "Excellent service! The agency helped me plan an incredible trip. Everything was perfectly organized.",
        "review_date_1": "October 15, 2023",
        "review_title_2": "Perfect vacation",
        "review_text_2": "Everything went exactly as we planned. The team was very professional and attentive.",
        "review_date_2": "November 5, 2023",
        "review_title_3": "100% Recommended",
        "review_text_3": "I couldn't have asked for better service. Every detail was taken care of.",
        "review_date_3": "December 20, 2023",
        "review_title_4": "Unique experience",
        "review_text_4": "The coffee tours were educational and delicious. I learned a lot about the coffee process.",
        "review_date_4": "January 10, 2024",
        "review_title_5": "Excellent organization",
        "review_text_5": "Everything was perfectly coordinated. The guides were knowledgeable and friendly.",
        "review_date_5": "February 5, 2024",
        "review_title_6": "Would return without hesitation",
        "review_text_6": "The combination of travel and coffee is great. The landscapes were breathtaking.",
        "review_date_6": "March 15, 2024",
        "review_title_7": "Exceptional service",
        "review_text_7": "The staff was very attentive and answered all our questions quickly.",
        "review_date_7": "April 1, 2024",
        "review_title_8": "Unforgettable trip",
        "review_text_8": "An experience I would repeat without hesitation. Everything was perfectly planned.",
        "review_date_8": "April 20, 2024",

        // Elementos comunes
        "contact": "Contact",
        "reviews": "Reviews",
        "about": "About Us",
        "help": "Help",
        "footer_address": "Av. Colón #200, Downtown, Tepeaca, Mexico",
        "footer_phone": "Phone: 223 101 1997",
        "footer_email": "Email: coffeetours.puebla@gmail.com",
        "reviews_link": "Reviews",
        "about_link": "About Us",
        "footer_disclaimer": "Coffee Tours is not responsible for the content of external websites.",
        "footer_copyright": "© 2025 Coffee Tours. All rights reserved.",
        "help_text": "Help"
    },
    pt: {
        // Página Principal
        "main_title": "Coffee Tours",
        "welcome_text": "Coffee Tours é um conceito inovador, combinando agência de viagens e café!",
        "search_placeholder": "Pesquisar...",
        "search_button": "Pesquisar",
        "view_button": "Ver",
        "quote_button": "Cotar",
        "book_button": "Reservar",
        "promotions_title": "Promoções",
        "paris_title": "Paris",
        "paris_alt": "Paris",
        "cuba_title": "Cuba",
        "cuba_alt": "Cuba",
        "cozumel_title": "Cozumel",
        "cozumel_alt": "Cozumel",
        "promo1_title": "Oferta Especial Paris",
        "promo1_text": "30% de desconto em passeios pela cidade!",
        "promo2_title": "2x1 em Cuba",
        "promo2_text": "Leve um acompanhante grátis",
        "promo3_title": "Pacote Cozumel",
        "promo3_text": "Tudo incluído a partir de $999",
        "promo4_title": "Oferta Especial",
        "promo4_text": "Descontos exclusivos",
        "promo5_title": "Oferta de Temporada",
        "promo5_text": "Pacotes especiais",
        "oferta1_alt": "Oferta Paris",
        "oferta2_alt": "Oferta Cuba",
        "oferta3_alt": "Oferta Cozumel",
        "oferta4_alt": "Oferta Especial",
        "oferta5_alt": "Oferta Temporada",

        // Página de Reserva
        "booking_title": "Reserva",
        "destination": "Destino: Roma, Itália.",
        "italy_img_alt": "Roma, Itália",
        "tab_description": "Descrição",
        "tab_itinerary": "Itinerário",
        "tab_prices": "Preços",
        "tab_testimonials": "Depoimentos",
        "tour_description": "Descubra a majestade de Roma, um destino onde a história ganha vida. Caminhe pelo Coliseu, jogue uma moeda na Fontana di Trevi e maravilhe-se com a grandiosidade do Vaticano. Desfrute da autêntica culinária italiana com pizzas, massas e gelato enquanto explora suas charmosas ruas de paralelepípedos.",
        "print_button": "Imprimir",
        "base_price": "$ Preço base",
        "start_date": "Data de início",
        "duration": "Duração",
        "duration_value": "6 dias, 5 noites",
        "people": "Pessoas",
        "option_1_person": "1 pessoa",
        "option_2_people": "2 pessoas",
        "option_3_people": "3 pessoas",
        "option_4_people": "4 pessoas",
        "option_5_people": "5 pessoas",
        "total": "Total",
        "continue_button": "Continuar reserva",

        // Página de Contacto
        "contact_title": "Contate-nos",
        "schedule_time": "9:00 am - 6:00 pm",
        "schedule_days": "Segunda a Sexta-feira",
        "social_title": "Redes Sociais",
        "instagram_handle": "agencia_de_viagens_coffeetours",
        "facebook_handle": "Agência de Viagens Coffee Tours",
        "location_title": "Localização",
        "map_alt": "Localização do Coffee Tours",
        "form_title": "Formulário de Contato",
        "name_label": "Nome completo *",
        "email_label": "Email *",
        "country_label": "País *",
        "phone_label": "Telefone *",
        "comments_label": "Observações",
        "submit_button": "Enviar",

        // Página de Checkout
        "checkout_title": "Finalizar Compra",
        "billing_title": "Detalhes de Faturamento",
        "name_label": "Nome *",
        "lastname_label": "Sobrenome *",
        "country_label": "País/Região *",
        "phone_label": "Telefone *",
        "email_label": "Endereço de e-mail *",
        "additional_info": "Informações adicionais",
        "your_order": "Seu Pedido",
        "product": "Produto",
        "description": "Descrição",
        "from": "De: Cidade do México",
        "to": "Para: Roma, Itália",
        "duration": "Duração: 6 dias, 5 noites",
        "persons": "Pessoas: 3",
        "subtotal": "Subtotal",
        "payment_method": "Método de Pagamento",
        "terms_conditions": "Termos e Condições",
        "place_order": "Finalizar Pedido",

        // Página de Registro
        "register_title": "Criar conta / Registro",
        "username_label": "Nome de usuário:",
        "email_label": "Email:",
        "password_label": "Senha:",
        "confirm_password_label": "Confirmar senha:",
        "register_button": "Registrar",
        "terms_text": "Ao continuar, você declara que leu e aceita nossos",
        "terms_link": "Termos e condições",
        "privacy_link": "Aviso de privacidade",
        "password_mismatch": "As senhas não coincidem",
        "password_length": "A senha deve ter pelo menos 8 caracteres",
        "invalid_email": "Digite um email válido",

        // Página de Inicio de Sesión
        "login_title": "Iniciar Sessão",
        "username": "Usuário",
        "password": "Senha",
        "login_button": "Entrar",
        "no_account": "Não tem uma conta?",
        "register_link": "Registe-se!",
        "username_placeholder": "Digite seu nome de usuário",
        "password_placeholder": "Digite sua senha",

        // Página de Reseñas
        "reviews_page_title": "Avaliações e Comentários",
        "reviews_title": "Avaliações e Comentários",
        "review_title_1": "Experiência incrível!",
        "review_text_1": "Serviço excelente! A agência me ajudou a planejar uma viagem incrível. Tudo foi perfeitamente organizado.",
        "review_date_1": "15 de outubro de 2023",
        "review_title_2": "Férias perfeitas",
        "review_text_2": "Tudo saiu exatamente como planejamos. A equipe foi muito profissional e atenciosa.",
        "review_date_2": "5 de novembro de 2023",
        "review_title_3": "Recomendado 100%",
        "review_text_3": "Não poderia ter pedido um serviço melhor. Cada detalhe foi cuidado ao máximo.",
        "review_date_3": "20 de dezembro de 2023",
        "review_title_4": "Experiência única",
        "review_text_4": "Os tours de café foram educativos e deliciosos. Aprendi muito sobre o processo do café.",
        "review_date_4": "10 de janeiro de 2024",
        "review_title_5": "Organização excelente",
        "review_text_5": "Tudo foi perfeitamente coordenado. Os guias eram conhecedores e amigáveis.",
        "review_date_5": "5 de fevereiro de 2024",
        "review_title_6": "Voltaria sem hesitar",
        "review_text_6": "A combinação de viagens e café é ótima. As paisagens eram impressionantes.",
        "review_date_6": "15 de março de 2024",
        "review_title_7": "Serviço excepcional",
        "review_text_7": "A equipe foi muito atenciosa e respondeu rapidamente a todas as nossas dúvidas.",
        "review_date_7": "1 de abril de 2024",
        "review_title_8": "Viagem inesquecível",
        "review_text_8": "Uma experiência que repetiria sem hesitação. Tudo foi perfeitamente planejado.",
        "review_date_8": "20 de abril de 2024",

        // Elementos comunes
        "contact": "Contato",
        "reviews": "Avaliações",
        "about": "Sobre Nós",
        "help": "Ajuda",
        "footer_address": "Av. Colón nº 200, Centro, Tepeaca, México",
        "footer_phone": "Telefone: 223 101 1997",
        "footer_email": "Email: coffeetours.puebla@gmail.com",
        "reviews_link": "Avaliações",
        "about_link": "Sobre Nós",
        "footer_disclaimer": "O Coffee Tours não é responsável pelo conteúdo de sites externos.",
        "footer_copyright": "© 2025 Coffee Tours. Todos os direitos reservados.",
        "help_text": "Ajuda"

        
    }
};